=== OmarDIOP0/jotaay/schema/messages.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="messages">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="message" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="message_id" type="xs:ID"/>
                            <xs:element name="sender_id" type="xs:IDREF"/>
                            <xs:choice>
                                <xs:element name="recipient" type="xs:IDREF" maxOccurs="unbounded"/>
                                <xs:element name="recipient_group" type="xs:IDREF"/>
                            </xs:choice>

                            <xs:element name="content" type="xs:string"/>
                            <xs:element name="file" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="read_by" type="xs:IDREFS" minOccurs="0"/>
                        </xs:sequence>
                        <xs:attribute name="timestamp" type="xs:dateTime" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== OmarDIOP0/jotaay/xmls/messages.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/messages.xsd">

 <message timestamp="2025-07-22T10:30:00">
        <message_id>u003</message_id>
        <sender_id>u001</sender_id>
        <recipient>u002</recipient>
        <recipient>u003</recipient>
        <content>Salut les amis, on se retrouve ce soir ?</content>
        <file>invitation.pdf</file>
        <read_by>u002 u003</read_by>
    </message>

    <!-- Message avec plusieurs fichiers -->
    <message timestamp="2025-07-22T13:45:00">
        <message_id>m004</message_id>
        <sender_id>u004</sender_id>
        <recipient_group>u005</recipient_group>
        <content>Voici les documents Ã  signer.</content>
        <file>contrat1.pdf</file>
        <file>contrat2.pdf</file>
        <read_by>u005</read_by>
    </message>
<message><id>68802f4b3c4fc</id><sender_id>687ff5a5962bd</sender_id><content/><timestamp>2025-07-23T00:39:39</timestamp><read_by/></message><message><id>68802f5730749</id><sender_id>687ff5a5962bd</sender_id><content/><timestamp>2025-07-23T00:39:51</timestamp><read_by/></message><message><id>6883f5585aa04</id><sender_id>687ff5a5962bd</sender_id><content>bonjour</content><timestamp>2025-07-25T21:21:28</timestamp><read_by/><recipient>771234567</recipient></message><message><id>6883f96776759</id><sender_id>687ff5a5962bd</sender_id><content>bonjour&#13;
</content><timestamp>2025-07-25T21:38:47</timestamp><read_by/><recipient>771234567</recipient></message><message><id>688400fb92693</id><sender_id>687ff5a5962bd</sender_id><content/><timestamp>2025-07-25T22:11:07</timestamp><read_by/></message><message><id>6884012c55c76</id><sender_id>687ff5a5962bd</sender_id><content/><timestamp>2025-07-25T22:11:56</timestamp><read_by/></message><message><id>688401e825a33</id><sender_id>687ff5a5962bd</sender_id><content/><timestamp>2025-07-25T22:15:04</timestamp><read_by/></message><message><id>68840217c9ade</id><sender_id>687ff5a5962bd</sender_id><content/><timestamp>2025-07-25T22:15:51</timestamp><read_by/></message><message><id>68861335c693f</id><sender_id>687ff5a5962bd</sender_id><content>bonjour</content><timestamp>2025-07-27T11:53:25</timestamp><read_by/><recipient>771234567</recipient></message><message><id>68861345076cb</id><sender_id>687ff5a5962bd</sender_id><content>salam</content><timestamp>2025-07-27T11:53:41</timestamp><read_by/><recipient>780987654</recipient></message><message><id>68861373cb482</id><sender_id>687ff5a5962bd</sender_id><content>bonjou</content><timestamp>2025-07-27T11:54:27</timestamp><read_by/><recipient>780987654</recipient></message><message><id>688613c1147ac</id><sender_id>687ff5a5962bd</sender_id><content>hey</content><timestamp>2025-07-27T11:55:45</timestamp><read_by/><recipient>780987654</recipient></message><message><id>6886146a341a8</id><sender_id>687ff5a5962bd</sender_id><content>what ?</content><timestamp>2025-07-27T11:58:34</timestamp><read_by/><recipient>780987654</recipient></message></messages>
